[package]
name = "tetris-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
serde.workspace = true
wasm-bindgen = { version = "0.2.100", optional = true, default-features = false }

[features]
wasm-bindgen = ["dep:wasm-bindgen"]
